### PR TITLE
'Download as an AppImage' banner

### PR DESCRIPTION
**Pull request by KhushrajRathod**
From https://github.com/AppImage/docs.appimage.org/pull/53
As per https://github.com/AppImage/docs.appimage.org/pull/53#pullrequestreview-468073400

- [x] Changed markdown to rst
- [x] File must be added to the repository
- [x] With credits
- [x] Under own headline

Let me know if you require further changes!

### CODE REVIEW

**Comment by KhushrajRathod** [comment]
@probonopd @TheAssassin
Please review!

**Comment by probonopd** [comment]
Thank you very much @KhushrajRathod.

What do you think @TheAssassin?

**Comment by TheAssassin** [comment]
Looks great! Thank you @KhushrajRathod!

**Comment by KhushrajRathod** [comment]
@probonopd @TheAssassin 
No problem 😄

**Comment by probonopd** [comment]
Thanks so much @KhushrajRathod

**Pull request merged**
