### PR TITLE
"Download as an AppImage" banner

### PR DESCRIPTION
**Pull request by probonopd**
https://github.com/AppImage/AppImageKit/issues/1065

### CODE REVIEW

**Comment by probonopd** [comment]
@TheAssassin please have a look, thanks!

**Comment by probonopd** [comment]
Maybe also consider @srevinsaju's version:

**Comment by TheAssassin** [comment]
I miss some proper round edges in the original . But it's a good base and could be improved. We should only have one version, though, this'll help people recognize the icon.

**Comment by probonopd** [comment]
Yes, I agree, some more work may be needed until this can be merged. Volunteers?

**Comment by srevinsaju** [comment]
I can add a `rst` version of the badge and the shield on `get-appimage` repository. Let me know if you require any changes on the shield and the badge 👌

**Comment by KhushrajRathod** [comment]
https://github.com/AppImage/docs.appimage.org/pull/55

**Pull request merged**
